Feature/spp 196/snapshot
ONSdigital/takeon-egestion pull request #15
Opened 2020-10-16 07:46 UTC by RyanAldy

2020-10-16 10:09 UTC, sivagudur commented on takeon-dbexport/main.go
> +		if strings.Contains(cdbExport, "Error loading data for db Export") {
This Bit we need to handle it correctly.  What's happening is on Error is it is continuing the process and creating an empty file in S3 bucket and send a success 'true' flag to output queue. It was supposed to not to create a file and send location=null and success=false to outputqueue

2020-10-16 10:11 UTC, sivagudur requested changes
Need changes in handling ''Error" string returning from Business layer

2020-10-19 10:15 UTC, mattprice-28 reviewed
Quick review, pulled down and run unit tests locally, all passing, can see the lambda in aws and expected behaviour in cloudwatch, in cloudwatch I can see the message 'Data from BL:' three times, the first time it has the expected data after the colon but the other two are blank

2020-10-19 10:23 UTC, mattprice-28 approved these changes
Tested again, looks better now, just the 'Data from bl inside else' statement which I assume was there for testing

2020-10-19 13:32 UTC, sivagudur approved these changes
All looks good to me and it is working as expected based on confluence document. I tested both success 'true' and 'false' scenarios.

2020-10-20 11:13 UTC, merged