Feature/spp 490/snapshot multi
ONSdigital/takeon-egestion pull request #19
Opened 2020-11-18 14:51 UTC by sufyaniqbal

# Description
Lambda file name change
https://collaborate2.ons.gov.uk/jira/browse/SPP-490

# How to test?
Pass a json message through the spp-es-takeon-egestion-spp490-db-export-input and check the lambda cloud watch log spp-es-takeon-egestion-spp490-export

Test env: spp490-snapshot
unit test

2020-11-18 15:01 UTC, dllmorgan requested changes

2020-11-18 15:01 UTC, dllmorgan commented on takeon-dbexport/main.go
> +			sendToSqs("", "null", false)
Is this sending an null/empty message to the output queue?

2020-11-18 15:35 UTC, dllmorgan requested changes

2020-11-18 15:35 UTC, dllmorgan commented on takeon-dbexport/main_test.go
> +}
These two tests need to check that no error has been returned.

2020-11-20 10:22 UTC, larissanne approved these changes
**Testing**

Correct JSON sent from input queue - Success:
Lambda logs show success

Invalid JSON sent from input queue - Fail:
Throws error in lambda logs

Extra digit in survey code from input queue - Fail:
Throws error in lambda logs

4 digit period from input queue i.e. for "201912" it was "1912" - Success:
Lambda logs show success

1 survey sent in JSON from input queue - Success:
Lambda logs show success

Period that doesn't exist - Fail:
Throws error in lambda logs

Empty JSON array sent from input queue for survey and period separately - Fail:
Throws error in lambda logs

Quotations need to be correct for message to be sent successfully and lambda to run successfuly

Timing was no more than 5 seconds for each scenario

2020-11-23 12:43 UTC, dllmorgan requested changes
re: The if statement inside getFileName (line 91) should be reversed. i.e. it is checking for an error condition and return the error message there and then. The rest of the function should be 'expected' behaviour. Having the usual return statement at the end of the function can be confusing for people to pick up.

2020-11-24 15:32 UTC, dllmorgan approved these changes

2020-11-24 16:14 UTC, merged