Feature/spp885/add logging to export lambda
ONSdigital/takeon-egestion pull request #26
Opened 2021-07-06 10:55 UTC by rhiGriff

# Description
Added spp-logger to dbexport lambda
https://collaborate2.ons.gov.uk/jira/browse/SPP-885 
Upgraded go to v 1.16 and added go.mod and go.sum files

# How to test?
In environment 1271

Send a message on the spp-es-takeon-egestion-spp1271-db-export-input queue

Example message:
{
	"snapshot_id": "14e0fb27-d450-44d4-8452-9f6996b00e27",
	"surveyperiods": [
	  {
		"survey": "023",
		"period": "201904"
	  },
	  {
		"survey": "023",
		"period": "201903"
	  },
	  {
		"survey": "066",
		"period": "201903"
	  },
	  {
		"survey": "067",
		"period": "201904"
	  }
	]
  }

Check cloudwatch logs.

Also please change log level to Debug and check

2021-07-08 13:35 UTC, fayaz0211 approved these changes
Tested the changes by sending the payload to the export queue and can able to see the export lambda logs for debug level and also verified the snapshot being upload to the export s3 bucket

2021-07-08 15:59 UTC, ranjit-das requested changes

2021-07-08 15:59 UTC, ranjit-das commented on takeon-dbexport/main.go
> +type LoggerContextStruct struct {
Looks like LoggerContextStruct is not used anywhere. So can it be removed?

2021-07-08 15:59 UTC, ranjit-das commented on takeon-dbexport/main.go
> +		Service:     "Validation",
Should Service be any other name e.g. Egestion or any other name that Dave can confirm?

2021-07-08 15:59 UTC, ranjit-das commented on takeon-dbexport/main.go
>  	fmt.Printf("DataToSend %v\n", string(DataToSend))
This Printf should be changed to logger.info/debug

2021-07-09 08:40 UTC, rhiGriff commented on takeon-dbexport/main.go
> +type LoggerContextStruct struct {
Good spot thank you

2021-07-09 09:27 UTC, ranjit-das approved these changes
Tested and found as expected

2021-07-09 09:45 UTC, merged